# Generated by Django 2.0.7 on 2020-04-18 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparable_name', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comps.Comparable'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
