# Generated by Django 2.0.7 on 2020-04-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0002_auto_20200418_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='base_tax_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='builder',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='homes_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='incentives',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='lot_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='market',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='monthly_hoa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='neighborhood',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='sales_start_date',
            field=models.DateTimeField(default='None', verbose_name='Community Start Range'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='survey_date',
            field=models.DateField(auto_now_add=True, default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='total_homes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='total_tax_rate',
            field=models.FloatField(default=0, verbose_name='Total Tax Rate'),
        ),
        migrations.AddField(
            model_name='choice',
            name='website',
            field=models.URLField(default='None'),
            preserve_default=False,
        ),
    ]
