# Generated by Django 2.0.7 on 2020-04-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0003_auto_20200419_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='sales_start_date',
            field=models.DateTimeField(),
        ),
    ]
